"""Initial migration

Revision ID: 8b4e993bc65d
Revises: 
Create Date: 2024-10-03 13:53:41.870149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4e993bc65d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Livre',
    sa.Column('id_livre', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('auteur', sa.String(length=100), nullable=True),
    sa.Column('date_publication', sa.Date(), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('disponibilite', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_livre')
    )
    op.create_table('Utilisateur',
    sa.Column('id_utilisateur', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('sysdate'), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_utilisateur')
    )
    op.create_index(op.f('ix_Utilisateur_email'), 'Utilisateur', ['email'], unique=True)
    op.create_table('Emprunt',
    sa.Column('id_emprunt', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('id_livre', sa.Integer(), nullable=False),
    sa.Column('date_emprunt', sa.DateTime(), server_default=sa.text('sysdate'), nullable=True),
    sa.Column('date_retour', sa.DateTime(), server_default=sa.text('sysdate'), nullable=True),
    sa.ForeignKeyConstraint(['id_livre'], ['Livre.id_livre'], ),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['Utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_emprunt'),
    sa.UniqueConstraint('id_utilisateur', 'id_livre', 'date_emprunt', name='UC_Emprunt')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Emprunt')
    op.drop_index(op.f('ix_Utilisateur_email'), table_name='Utilisateur')
    op.drop_table('Utilisateur')
    op.drop_table('Livre')
    # ### end Alembic commands ###
