"""Initial migration 2  

Revision ID: af1c1d35d750
Revises: 8b4e993bc65d
Create Date: 2024-10-03 13:58:49.424249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af1c1d35d750'
down_revision: Union[str, None] = '8b4e993bc65d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Emprunt',
    sa.Column('id_emprunt', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('id_livre', sa.Integer(), nullable=False),
    sa.Column('date_emprunt', sa.DateTime(), server_default=sa.text('sysdate'), nullable=True),
    sa.Column('date_retour', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_livre'], ['Livre.id_livre'], ),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['Utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_emprunt'),
    sa.UniqueConstraint('id_utilisateur', 'id_livre', 'date_emprunt', name='UC_Emprunt')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Emprunt')
    # ### end Alembic commands ###
